stages:
  - client
  - server

jobs:
  include:
  - stage: client
    language: android
    os: linux
    sudo: true
    android:
      components:
      - tools
      - platform-tools
      - tools
      - build-tools-26.0.2
      - android-26
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
    addons:
      apt:
        packages:
        - oracle-java8-installer
        - oracle-java8-set-default
        - npm
        - jq
    before_install:
      - export LANG=en_US.UTF-8
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; 
          brew install npm ios-sim jq ios-deploy cocoapods ; 
          rvm use system ; 
          pod setup ; 
        fi
      - nvm install 8
      - npm install -g cordova ionic
    script:
      # install build dependecies
      - cd $TRAVIS_BUILD_DIR/client/mobile-ticket-queue
      - npm install

      # - install plugins etc.
      - ionic cordova plugin add https://github.com/EddyVerbruggen/Custom-URL-scheme.git --variable URL_SCHEME=mobileticket
      - cordova prepare

      # build Android and iOS packages
      - ionic build --prod
      - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then ionic cordova build ios --prod --device --release ; fi
      - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
          ionic cordova build android --prod --release ;
          ${ANDROID_HOME}/build-tools/26.0.2/zipalign -v -p 4 $TRAVIS_BUILD_DIR/client/mobile-ticket-queue/platforms/android/build/outputs/apk/android-release-unsigned.apk $TRAVIS_BUILD_DIR/outputs/client/release/mbq-release-unsigned-aligned.apk ;
        fi
      - cp -R -f ./www $TRAVIS_BUILD_DIR/src/main/resources/app
  - stage: server
    language: scala
    os: linux
    script:
      - cd $TRAVIS_BUILD_DIR
      - sbt assembly
      - cp -f $TRAVIS_BUILD_DIR/target/scala*/*.jar $TRAVIS_BUILD_DIR/outputs/server/release

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/transforms*/
- rm -rf $HOME/.gradle/caches/3.5/fileHashes/
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
# - rm -f  $HOME/.gradle/caches/transforms-1/transforms-1.lock

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_script:
  # update npm and cordova dependencies
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./travis/addkeys.sh ; fi
  - mkdir -p $TRAVIS_BUILD_DIR/outputs/client/release
  - mkdir -p $TRAVIS_BUILD_DIR/outputs/server/release

env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle

after_success:
  # generate documentation
  # - gulp doc

deploy:
  # deploy build to s3
  provider: s3
  access_key_id: $aws_user
  secret_access_key: $aws_accesskey
  region: "eu-west-1"
  bucket: "rs-travis"
  local_dir: $TRAVIS_BUILD_DIR/outputs
  upload_dir: mobile-ticket-queue
  skip_cleanup: true
